# Generated by Django 4.2.6 on 2023-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
