# Generated by Django 4.2.6 on 2023-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_block_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Короткое описание темы'),
        ),
    ]
