# Generated by Django 4.2.6 on 2023-12-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_course',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
