# Generated by Django 4.2.6 on 2023-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_time_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_course',
            field=models.PositiveIntegerField(default=0, verbose_name='Вреямя на изучение'),
        ),
    ]
