# Generated by Django 4.2.6 on 2023-11-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
