# Generated by Django 4.2.6 on 2023-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_answer_options_alter_question_options_and_more'),
        ('user', '0004_delete_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
