# Generated by Django 4.2.6 on 2023-12-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_registration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseProgress',
        ),
    ]
